version: "1.0"

stages:
  - clone
  - prepare
  - build
  - unit-test
  - integration-test
  - build-docker-images
  - deploy

indicators:
  - environment: &global_env
      - FR_PRIVATE_REPO_USER=${{FR_PRIVATE_REPO_USER}}
      - FR_PRIVATE_REPO_PASSWORD=${{FR_PRIVATE_REPO_PASSWORD}}
      - GITHUB_GPG_KEY_ID=${{GITHUB_GPG_KEY_ID}}
      - GITHUB_GPG_KEY=${{GITHUB_GPG_KEY}}
      - GITHUB_ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}

steps:
  #  Clone stage
  main_clone:
    title: Cloning main repository...
    stage: "clone"
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'


  #  Prepare stage
  check-copyright:
    image: r.cfcr.io/openbanking/ob-release:latest
    stage: "prepare"
    title: "Verify copyrights"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository license:check
    environment: *global_env
  # Build stage
  build-stage:
    stage: "build"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Compile, build and install artifact"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Ddockerfile.skip -DdockerCompose.skip -DskipTests -DskipITs clean install -T 8
    environment: *global_env

  # unit test stage
  test-stage:
    stage: "unit-test"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Run unit tests"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -DdockerCompose.skip -Ddockerfile.skip -DskipITs verify
    environment: *global_env

  #Run IT test
  integration-test-rs-gateway:
    type: composition
    stage: "integration-test"
    title: "RS Gateway integration tests"
    description: "Start docker services via docker-compose and run rs-gateway integration tests"
    working_directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server
    composition: docker-compose.yml
    composition_candidates:
      rs-api-tests:
        volumes:
          - ${{CF_VOLUME}}:/codefresh/volume
        image: r.cfcr.io/openbanking/ob-release:latest
        environment: *global_env
        command:  mvn -Dspring.cloud.config.uri=http://config.dev-ob.forgerock.financial:8888 -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Dspring.data.mongodb.uri=mongodb://mongo:27017/test -Ddockerfile.skip -DdockerCompose.skip verify -f /codefresh/volume/${{CF_REPO_NAME}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server/pom.xml
        hostname: rs-api
  integration-test-rs-mock-store:
    type: composition
    stage: "integration-test"
    title: "RS Store integration tests"
    description: "Start docker services via docker-compose and run rs-store integration tests"
    working_directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-mock-store/forgerock-openbanking-uk-aspsp-rs-mock-store-server
    composition: docker-compose.yml
    composition_candidates:
      rs-store-tests:
        volumes:
          - ${{CF_VOLUME}}:/codefresh/volume
        image: r.cfcr.io/openbanking/ob-release:latest
        environment: *global_env
        command:  mvn -Dspring.cloud.config.uri=http://config.dev-ob.forgerock.financial:8888 -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Dspring.data.mongodb.uri=mongodb://mongo:27017/test -Ddockerfile.skip -DdockerCompose.skip verify -f /codefresh/volume/${{CF_REPO_NAME}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-mock-store/forgerock-openbanking-uk-aspsp-rs-mock-store-server/pom.xml
        hostname: rs-store
  integration-test-rs-rcs:
    type: composition
    stage: "integration-test"
    title: "RS RCS integration tests"
    description: "Start docker services via docker-compose and run rs-rcs integration tests"
    working_directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-rcs/forgerock-openbanking-uk-aspsp-rs-rcs-server
    composition: docker-compose.yml
    composition_candidates:
      rs-rcs-tests:
        volumes:
          - ${{CF_VOLUME}}:/codefresh/volume
        image: r.cfcr.io/openbanking/ob-release:latest
        environment: *global_env
        command:  mvn -Dspring.cloud.config.uri=http://config.dev-ob.forgerock.financial:8888 -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Dspring.data.mongodb.uri=mongodb://mongo:27017/test -Ddockerfile.skip -DdockerCompose.skip verify -f /codefresh/volume/${{CF_REPO_NAME}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-rcs/forgerock-openbanking-uk-aspsp-rs-rcs-server/pom.xml
        hostname: rs-rcs

  #Docker build
  build-rs-gateway-sample-docker-image:
    type: build
    title: "Build RS gateway sample service docker image"
    stage: "build-docker-images"
    image_name: obri/rs-api-sample
    working-directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-sample
    build_arguments:
      - JAR_FILE=target/forgerock-openbanking-*.jar
      - VERSION_FILE=target/VERSION
      - SERVICE_FILE=target/SERVICE
  build-rs-mock-store-sample-docker-image:
    type: build
    title: "Build RS mock store sample service docker image"
    stage: "build-docker-images"
    image_name: obri/rs-store-sample
    working-directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-mock-store/forgerock-openbanking-uk-aspsp-rs-mock-store-sample
    build_arguments:
      - JAR_FILE=target/forgerock-openbanking-*.jar
      - VERSION_FILE=target/VERSION
      - SERVICE_FILE=target/SERVICE
  build-rs-rcs-sample-docker-image:
    type: build
    title: "Build RS RCS sample service docker image"
    stage: "build-docker-images"
    image_name: obri/rs-rcs-sample
    working-directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-rcs/forgerock-openbanking-uk-aspsp-rs-rcs-sample
    build_arguments:
      - JAR_FILE=target/forgerock-openbanking-*.jar
      - VERSION_FILE=target/VERSION
      - SERVICE_FILE=target/SERVICE

  disable-include-administrator:
    title: "temporarily disable include administrators"
    stage: "deploy"
    image: benjjefferies/branch-protection-bot
    environment:
      - ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
      - OWNER=${{CF_REPO_OWNER}}
      - REPO=${{CF_REPO_NAME}}
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'

  # deploy jar stage
  deploy-master:
    title: "deploy jars to private maven repo"
    stage: "deploy"
    image: r.cfcr.io/openbanking/ob-release:latest
    working-directory: ${{main_clone}}
    commands:
      - git checkout $CF_BRANCH
      - git reset --hard origin/$CF_BRANCH
      - release.sh /codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository
    environment: *global_env
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'

  enable-include-administrator:
    title: "enable include administrators"
    stage: "deploy"
    image: benjjefferies/branch-protection-bot
    environment:
      - ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}
      - OWNER=${{CF_REPO_OWNER}}
      - REPO=${{CF_REPO_NAME}}
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'