version: "1.0"

stages:
  - clone
  - prepare
  - build
  - unit-test
  - integration-test
  - build-docker-images
  - deploy

indicators:
  - environment: &global_env
      - FR_PRIVATE_REPO_USER=${{FR_PRIVATE_REPO_USER}}
      - FR_PRIVATE_REPO_PASSWORD=${{FR_PRIVATE_REPO_PASSWORD}}
      - GITHUB_GPG_KEY_ID=${{GITHUB_GPG_KEY_ID}}
      - GITHUB_GPG_KEY=${{GITHUB_GPG_KEY}}
      - GITHUB_ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}

steps:
  #  Clone stage
  main_clone:
    title: Cloning main repository...
    stage: "clone"
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'

  #  Prepare stage
  check-copyright:
    image: r.cfcr.io/openbanking/ob-release:latest
    stage: "prepare"
    title: "Verify copyrights"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository license:check
    environment: *global_env
  # Build stage
  build-stage:
    stage: "build"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Compile, build and install artifact"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -Ddockerfile.skip -DdockerCompose.skip -DskipTests -DskipITs clean install -T 8
    environment: *global_env

  # unit test stage
  test-stage:
    stage: "unit-test"
    image: r.cfcr.io/openbanking/ob-release:latest
    title: "Run unit tests"
    working-directory: ${{main_clone}}
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository -DdockerCompose.skip -Ddockerfile.skip -DskipITs verify
    environment: *global_env

  #Run IT test
  integration-test-rs-api:
    type: composition
    stage: "integration-test"
    title: "RS API integration tests"
    description: "Start docker services via docker-compose and run rs-api integration tests"
    composition: docker-compose.yml
    composition_variables:
      - TAG=:${{TAG_VERSION}}
    working_directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server
    composition_candidates:
      rs-api-tests:
        volumes:
          - ${{CF_VOLUME}}:/codefresh/volume
        image: r.cfcr.io/openbanking/ob-release:latest
        environment: *global_env
        command: mvn -Dmaven.repo.local=/codefresh/volume/$1/.m2/repository  -Dspring.data.mongodb.uri=mongodb://mongo:27017/test -Ddockerfile.skip -DdockerCompose.skip verify -f /codefresh/volume/ob-aspsp/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server/pom.xml
        hostname: rs-api

  #Docker build
  build-rs-store-sample-docker-image:
    type: build
    title: "Build rs-store sample service docker image"
    stage: "build-docker-images"
    image_name: obri/rs-store
    working-directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-mock-store/forgerock-openbanking-uk-aspsp-rs-mock-store-sample
    build_arguments:
      - JAR_FILE=target/forgerock-openbanking-*.jar
      - VERSION_FILE=target/VERSION
      - SERVICE_FILE=target/SERVICE
    tag: ${{TAG_VERSION}}



  # deploy jar stage
  deploy-master:
    title: "deploy jars to private maven repo"
    stage: "deploy"
    image: r.cfcr.io/openbanking/ob-release:latest
    working-directory: ${{main_clone}}
    commands:
      - git checkout $CF_BRANCH
      - git reset --hard origin/$CF_BRANCH
      - release.sh /codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository
    environment: *global_env
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "[maven-release-plugin]") == false'
          masterBranch: '"${{CF_BRANCH}}" == "master"'