version: "1.0"

stages:
  - clone
  - prepare
  - build
  - unit-test
  - integration-test
  - build-docker-images
  - deploy

indicators:
  - environment: &global_env
      - FR_PRIVATE_REPO_USER=${{FR_PRIVATE_REPO_USER}}
      - FR_PRIVATE_REPO_PASSWORD=${{FR_PRIVATE_REPO_PASSWORD}}
      - GITHUB_GPG_KEY_ID=${{GITHUB_GPG_KEY_ID}}
      - GITHUB_GPG_KEY=${{GITHUB_GPG_KEY}}
      - GITHUB_ACCESS_TOKEN=${{GITHUB_ACCESS_TOKEN}}

steps:
  #  Clone stage
  main_clone:
    title: Cloning main repository...
    stage: "clone"
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    
  #Run IT test
  integration-test-rs-gateway:
    type: composition
    stage: "integration-test"
    title: "RS Gateway integration tests"
    description: "Start docker services via docker-compose and run rs-gateway integration tests"
    composition: docker-compose.yml
    composition_variables:
      - TAG=:${{TAG_VERSION}}
    working_directory: ${{main_clone}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server
    composition_candidates:
      rs-api-tests:
        volumes:
          - ${{CF_VOLUME}}:/codefresh/volume
        image: r.cfcr.io/openbanking/ob-release:latest
        environment: *global_env
        commands:
          - ls; pwd;
          - mvn -Dmaven.repo.local=/codefresh/volume/${{CF_BRANCH_TAG_NORMALIZED}}/.m2/repository  -Dspring.data.mongodb.uri=mongodb://mongo:27017/test -Ddockerfile.skip -DdockerCompose.skip verify -f /codefresh/volume/${{CF_REPO_NAME}}/forgerock-openbanking-uk-aspsp-rs/forgerock-openbanking-uk-aspsp-rs-gateway/forgerock-openbanking-uk-aspsp-rs-gateway-server/pom.xml
        hostname: rs-api
