export enum IntentType {
  ACCOUNT_ACCESS_CONSENT = 'ACCOUNT_ACCESS_CONSENT',
  PAYMENT_SINGLE_REQUEST = 'PAYMENT_SINGLE_REQUEST',
  PAYMENT_DOMESTIC_CONSENT = 'PAYMENT_DOMESTIC_CONSENT',
  PAYMENT_DOMESTIC_SCHEDULED_CONSENT = 'PAYMENT_DOMESTIC_SCHEDULED_CONSENT',
  PAYMENT_DOMESTIC_STANDING_ORDERS_CONSENT = 'PAYMENT_DOMESTIC_STANDING_ORDERS_CONSENT',
  PAYMENT_INTERNATIONAL_CONSENT = 'PAYMENT_INTERNATIONAL_CONSENT',
  PAYMENT_INTERNATIONAL_SCHEDULED_CONSENT = 'PAYMENT_INTERNATIONAL_SCHEDULED_CONSENT',
  PAYMENT_INTERNATIONAL_STANDING_ORDERS_CONSENT = 'PAYMENT_INTERNATIONAL_STANDING_ORDERS_CONSENT',
  PAYMENT_FILE_CONSENT = 'PAYMENT_FILE_CONSENT',
  FUNDS_CONFIRMATION_CONSENT = 'FUNDS_CONFIRMATION_CONSENT',
  DOMESTIC_VRP_PAYMENT_CONSENT = 'DOMESTIC_VRP_PAYMENT_CONSENT',
  CUSTOMER_INFO_CONSENT = 'CUSTOMER_INFO_CONSENT'
}
