version: '2'
services:
 config-rs-api:
  container_name: config-rs-api
  image: eu.gcr.io/openbanking/obri/config
  ports:
   - "38888:8888"
  environment:
   - spring_profiles_active=native,console-logging
  networks:
   default:
    aliases:
    - config.dev-ob.forgerock.financial
 mongo-rs-store:
  container_name: mongo-rs-api
  image: mongo
  ports:
  - "57020:27017"
  networks:
   default:
    aliases:
    - mongo