/**
 * Copyright 2019 ForgeRock AS. All Rights Reserved
 *
 * Use of this code requires a commercial software license with ForgeRock AS.
 * or with one of its affiliates. All use shall be exclusively subject
 * to such license between the licensee and ForgeRock AS.
 */
package com.forgerock.openbanking.common.model.openbanking.forgerock.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.domain.Persistable;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import uk.org.openbanking.datamodel.event.OBEventPolling1SetErrs;

/**
 * An event generated by an ASPSP that a third-party user of the sandbox may be interested in.
 * Examples include: payment processing and consent revocation.
 * Events are intended for occurrences that originate in the bank simulation or from a PSU. i.e. things the TPP would not be aware of.
 * Creation and authorisation of consents are performed by the TPP via REST and should not require an event as the TPP gets a REST response as part of the action.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document
public class FREventNotification implements Persistable<String> {

    @Id
    @Indexed
    public String id;

    @Indexed
    public String jti;

    public String signedJwt;

    @Indexed
    public String tppId;

    @CreatedDate
    public DateTime created;
    @LastModifiedDate
    public DateTime updated;

    public OBEventPolling1SetErrs errors;

    @Override
    public boolean isNew() {
        return created == null;
    }

    public boolean hasErrors() {
        return errors!=null;
    }


}
